#!/bin/bash

python /usr/lib/raspiwifi/configuration_app/rtcTime.py & 

python /usr/lib/raspiwifi/configuration_app/feedTimer.py & 

cd /usr/lib/raspiwifi/configuration_app/server/ ; sudo node app.js &

hostapd -dd /etc/hostapd/hostapd.conf &
